### ISSUE TITLE
XSS攻撃対策を行う

### ISSUE THREAD

**Issue by hamuhamu** [Lesmoinc/lesmo-web#48]
# 概要

XSS対策用のコードを入れていない。
もしかするとrender時にフレームワークの方でよしなにやってくれているかもしれない。

仕組みの理解と必要であれば対策を行う。

**Comment by hamuhamu** [comment]
@CASIXx1 
erbのコード読んで問題なさそうならcloseしちゃってくださいw

**Comment by CASIXx1** [comment]
@hamuhamu 
りょかいです 🆗

**Comment by CASIXx1** [comment]
一応全部のviewに目を通しました笑

おkそうです。
別件ですが、Strong Parameterを使ってないので、そこは少し心配。
ベットissue化します :octocat:

**Comment by hamuhamu** [comment]
Strong Parameterは一旦無視してましたw

今はバリデーション無しでやってます笑

まだ、プロトタイプ検証もしておらず入力項目に変更がある可能性があるのでかなりザルですw
